sonnie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('sonnie_app.urls')),
]

sonnie_app/urls.py
"""Defines URL patterns for sonnie_app."""

from django.urls import path

from . import views

app_name = 'sonnie_app'
urlpatterns = [
	# home page
	path('', views.index, name='index'),

	# show all recipes
	path('recipes/', views.recipes, name='recipes'),

	# detail page for a single topic
	path('recipes/<int:recipe_id>', views.recipe, name='recipe'),

	# page for adding a new topic
	path('new_recipe/', views.new_recipe, name='new_recipe'),

	# page for adding a new entry
	path('new_entry/<int:recipe_id>', views.new_entry, name='new_entry'),

	# page for editing an entry
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
	
]

users/urls.py
"""Defines url patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
	# login page
	path('login/',
    	auth_views.LoginView.as_view(template_name='users/login.html'),
    	name='login'),

	# logout page
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),

	# registration page
	path('register/', views.register, name='register'),
]

sonnie_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Recipe(models.Model):
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

class Entry(models.Model):
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

sonnie_app/forms.py
from django import forms

from .models import Recipe, Entry

class RecipeForm(forms.ModelForm):
	class Meta:
		model = Recipe
		fields = ['text']
		labels = {'text':''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

sonnie_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Recipe, Entry
from .forms import RecipeForm, EntryForm

def index(request):
	"""The home page for learning log"""
	return render(request, 'sonnie_app/index.html')

@login_required
def recipes(request):
	# show all topics
	recipes = Recipe.objects.filter(owner=request.user).order_by('date_added')
	context = {'recipes': recipes}
	return render(request, 'sonnie_app/recipes.html', context)

@login_required
def recipe(request, recipe_id):
	# show a single topic and all its entries
	recipe = Recipe.objects.get(id=recipe_id)
	if recipe.owner != request.user:
		raise Http404
	entries = recipe.entry_set.order_by('-date_added')
	context = {'recipe': recipe, 'entries': entries}
	return render(request, 'sonnie_app/recipe.html', context)

@login_required
def new_recipe(request):
	# add a new topic
	if request.method != 'POST':
		# no data submitted, create blank form
		form = RecipeForm()
	else:
		# POST data submitted, process data
		form = RecipeForm(request.POST)
		if form.is_valid():
			new_recipe = form.save(commit=False)
			new_recipe.owner = request.user
			new_recipe.save()
			return HttpResponseRedirect(reverse('sonnie_app:recipes'))

	context = {'form': form}
	return render(request, 'sonnie_app/new_recipe.html', context)

@login_required
def new_entry(request, recipe_id):
	# add new entry for a particular topic
	recipe = Recipe.objects.get(id=recipe_id)

	if request.method != 'POST':
		# no data submitted , create blank form
		form = EntryForm()
	else:
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.recipe = recipe
			new_entry.save()
			return HttpResponseRedirect(reverse('sonnie_app:recipe', args=[recipe_id]))

	context = {'recipe': recipe, 'form': form}
	return render(request, 'sonnie_app/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	# add new entry for a particular topic
	entry = Entry.objects.get(id=entry_id)
	recipe = entry.recipe
	if recipe.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# initial request, pre-fill form with current entry
		form = EntryForm(instance=entry)
	else:
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('sonnie_app:recipe', args=[recipe.id]))

	context = {'entry': entry,'recipe': recipe, 'form': form}
	return render(request, 'sonnie_app/edit_entry.html', context)

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
	"""Log the user out."""

	logout(request)

	return HttpResponseRedirect(reverse('sonnie_app:index'))

def register(request):
	# register a new user
	if request.method != 'POST':
		# dispay blank registration form
		form = UserCreationForm()
	else:
		# process comleted form
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# login user & redirect to home page
			authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('sonnie_app:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

sonnie_app/templates/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Sharon's Cookbook</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>
<body>
	<!-- Static navbar -->
	<nav class="navbar navbar-default navbar-static-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			</button>
			<a class="navbar-brand" href="{% url 'learning_logs:index' %}">Sharon's Cookbook</a>
		</div>

		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>
					<a href="{% url 'sonnie_app:recipes' %}">Recipes</a>
				</li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li><a> Hello, {{ user.username }}</a></li>
					<li><a href="{% url 'users:logout' %}">log out</a></li>
				{% else %}
					<li><a href="{% url 'users:register' %}">register</a></li>
					<li><a href="{% url 'users:login' %}">log in  </a></li>
				{% endif %}
			</ul>
		</div><!--/.nav-collapse--> 
	</nav>

	<div class="container">
		<div class="page-header">
			{% block header %}{% endblock header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</div> <!-- /container -->
</body>
</html>

sonnie_app/templates/sonnie_app/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Sharon's Cookbook</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>
<body>
	<!-- Static navbar -->
	<nav class="navbar navbar-default navbar-static-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			</button>
			<a class="navbar-brand" href="{% url 'sonnie_app:index' %}">Sharon's Cookbook</a>
		</div>

		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>
					<a href="{% url 'sonnie_app:recipes' %}">Recipes</a>
				</li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li><a> Hello, {{ user.username }}</a></li>
					<li><a href="{% url 'users:logout' %}">log out</a></li>
				{% else %}
					<li><a href="{% url 'users:register' %}">register</a></li>
					<li><a href="{% url 'users:login' %}">log in  </a></li>
				{% endif %}
			</ul>
		</div><!--/.nav-collapse--> 
	</nav>

	<div class="container">
		<div class="page-header">
			{% block header %}{% endblock header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</div> <!-- /container -->
</body>
</html>

sonnie_app/templates/sonnie_app/edit_entry.html
{% extends "sonnie_app/base.html" %}

{% block content %}

	<p><a href="{% url 'sonnie_app:recipe' recipe.id %}">{{ recipe }}</a></p>

	<p>Edit entry:</p>

	<form action="{% url 'sonnie_app:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">save changes</button>
	</form>

{% endblock content%}

sonnie_app/templates/sonnie_app/index.html
{% extends "sonnie_app/base.html" %}

{% block header %}
	<div class='jumbotron'>
		<h2>Track your favorite recipes. Access them from any place on Earth</h2>
	</div>
{% endblock header %}

{% block content %}
	<h3>
		<a href="{% url 'users:register' %}"><strong>Register an account</strong></a> 
	</h3>
	<h3>
		<a href="{% url 'users:login' %}">Log in</a> to view your recipes , edit them and note down any new recipe you've picked up.
	</h3>
	
{% endblock content %}

sonnie_app/templates/sonnie_app/new_entry.html
{% extends "sonnie_app/base.html" %}

{% block content %}

	<p><a href="{% url 'sonnie_app:recipe' recipe.id %}">{{ recipe }}</a></p>

	<p>Add a new entry:</p>

	<form action="{% url 'sonnie_app:new_entry' recipe.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add entry</button>
	</form>

{% endblock content%}

sonnie_app/templates/sonnie_app/new_recipe.html
{% extends "sonnie_app/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Add a new recipe</h2>
{% endblock header %}

{% block content%}

	<form action="{% url 'sonnie_app:new_recipe' %}" method='post' class="form">

		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<button name="submit" class="btn btn-primary">add recipe</button>
		{% endbuttons %}

	</form>

{% endblock content %}

sonnie_app/templates/sonnie_app/recipe.html
{% extends 'sonnie_app/base.html' %}
{% block header %}
	<h2>{{ recipe }}</h2>
{% endblock header %}

{% block content %}

	<p>
		<a href="{% url 'sonnie_app:new_entry' recipe.id %}">add new entry</a>
	</p>
	
	{% for entry in entries %}
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3>
				{{ entry.date_added|date:'M d, Y H:i' }}
				<small>
					<a href="{% url 'sonnie_app:edit_entry' entry.id %}">edit entry</a>
				</small>
			</h3>
		</div>
	</div>
	<div class="panel-body">
		{{ entry.text|linebreaks }}
	</div>
	{% empty %}
		There are no entries for this recipe yet
	{% endfor %}		
	

{% endblock content%}

sonnie_app/templates/sonnie_app/recipes.html
{% extends "sonnie_app/base.html" %}

{% block header %}
	<h1>Recipe</h1>
{% endblock header %}

{% block content %}

	<ul>
		{% for recipe in recipes %}
			<li>
				<h3>
					<a href="{% url 'sonnie_app:recipe' recipe.id %}">{{ recipe }}</a>
				</h3>
			</li>
		{% empty %}
			<li>No recipes have been specified</li>
		{% endfor %}
	</ul>

	<h3><a href="{% url 'sonnie_app:new_recipe' %}">Add a new recipe</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "sonnie_app/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}

	{% if form.errors %}
	<p>Your username and password didn't match. Please try again</p>
	{% endif %}

	<form method="post" action="{% url 'users:login' %}" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">log in</button>
		{% endbuttons %}

		<input type="hidden" name="next" value="{% url 'sonnie_app:index' %}">
	</form>

{% endblock content%}

users/templates/users/register.html
{% extends "sonnie_app/base.html" %}

{% block content %}

	<form method="post" action="{% url 'users:register' %}">
		{% csrf_token %}
		{{  form.as_p}}

		<button name="submit">register</button>
		<input type="hidden" name="next" value="{% url 'sonnie_app:index' %}">
	</form>

{% endblock content %}